{% set name = "pscript" %}
{% set version = "0.7.5" %}
{% set sha256 = "9217a291477af34833bef1880191467c8dda1bb09052e5f142b46904088e980d" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  number: 1

requirements:
  host:
    - python >=2.7,<3|>=3.5
    - pip
  run:
    - python >=2.7,<3|>=3.5

test:
  imports:
    - pscript

about:
  home: http://pscript.readthedocs.io
  doc_url: http://pscript.readthedocs.io
  dev_url: https://github.com/flexxui/pscript
  summary: library for transpiling Python code to JavaScript.
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - almarklein
