{% set name = "pscript" %}
{% set version = "0.7.2" %}
{% set sha256 = "7cd6da5e1ba69b6f1058bae903841343adec06e64585de01b64739c9a64983c0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  number: 0

requirements:
  build:
    - python
    - pip
  run:
    - python

test:
  imports:
    - pscript

about:
  home: http://pscript.readthedocs.io
  doc_url: http://pscript.readthedocs.io
  dev_url: https://github.com/flexxui/pscript
  summary: library for transpiling Python code to JavaScript.
  license: BSD 2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - almarklein
