{% set name = "pscript" %}
{% set version = "0.7.6" %}
{% set sha256 = "ef2f50f2508e9bea58540dc5d7307691b169b104156a1c7a1366c1bd1bd69377" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  number: 0

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - pscript

about:
  home: http://pscript.readthedocs.io
  doc_url: http://pscript.readthedocs.io
  dev_url: https://github.com/flexxui/pscript
  summary: library for transpiling Python code to JavaScript.
  license: BSD 2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - almarklein
